[package]
name = "dracarys"
version = "0.0.1"
authors = ["Younis Shah <younisashah@gmail.com>"]

[dependencies]
reqwest = "0.7.2"
hyper = "0.11.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"